version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./dataset:/dataset  # Mounting dataset folder

  mongo:
    image: mongo
    ports:
      - "27017:27017"
